session_name: Devman-Demo
windows:
  - window_name: Devman_Demo
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/devman-templates/devman-repo
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" devman-templates/devman-repo
        focus: true
      - clear
